spring:
  application:
    name: fancy-url-shortener
    redirect-base-url: "http://localhost:8080/r/"
  cassandra:
    keyspace-name: fancy_url_shortener
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: none
